# syntax=docker/dockerfile:1
# FROM bitnami/mediawiki:latest
# RUN apk add vim
# WORKDIR /
# COPY . .
# RUN yarn install --production
# CMD ["node", "src/index.js"]

FROM bitnami/mediawiki:latest

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV HOME = /root